Помощь <F1>, выход <Alt-X> или <Esc>_
Экран соранен в файле "pcx"_
Ошибка в имени файла_
Ошибка в заданной функции_
Информация_
Сеточные множества_
Сеточная граница_
Значения параметров_
шаг сетки_
размер квадрата_
параметр границы k =_
Сеточная плотность_
Разностный потенциал uN+_
Разностный потенциал uN-_
Сумма потенциалов на границе_
Посчитайте сначала оба потенциала_
Посчитайте сначала этот потенциал_
След точного решения u(x,y)_
Разностный потенциал uN_
Отклонение потенциала u(x,y)-uN_
Нормальная производная_
Сеточная плотность задана_
Посчитайте сначала плотность_
  Значения_
 параметров_
 u(x,y)_
      -x_
   x^2 - y^2_
 x^3 - 3*x*y^2_
  y/(x^2+y^2)_
x*y/(x^2+y^2)^2_
