7 1
4 1 -1 1 *__
Информация о авторах
21 1 -1 1 Файлы___
Операции с файлами
19 1 -1 1 Окна___
Операции с окнами
23 1 -1 1 Запуск___
Счет задачи. Прервать-ESC
17 1 -1 1 Методы____
Выбор метода решения
20 1 -1 1 Параметры____
Выбор параметров задачи
0 1 -1 1 Помощь____
Выдача помощи
1 2
11 4 -1 1( ) Линейная задача   @
Выбор метода решения
18 4 -1 1( ) Нелинейная задача @
Выбор метода решения
1 3
10 4 -1  1( ) Разностная прогонка исходного ур-ния
Решение прогонкой
16 4 -1  1( ) Общее решение:   з. Коши
Построение общего решения
16 4 -1  1( ) Общее решение:  разностная прогонка
Построение общего решения
1 2
15 4 -1 1( ) Метод стрельбы 
Решение методом стрельбы
13 4 -1 1( ) Линеаризация  @
Линеаризация уравнения
1 4
13 0 -1 0  Методы решения линеаризованного ур-ния:
10 4 -1 1( ) Разностная прогонка лин. ур-ния
Решение прогонкой
16 4 -1 1( ) Общее решение:   з. Коши
Построение общего решения
16 4 -1 1( ) Общее решение:  разностная прогонка
Построение общего решения
2 6
20 1 7 1 t(x)= 1.0___________
Редактирование - пробел
20 1 7  1 p(x)= 1000.0_______
Редактирование - пробел
20 1 7  1 q(x)= 0____________
Редактирование - пробел
20 1 4 1 N= 200_
Редактирование - пробел
20 0 5 1 a1= 1____
Редактирование - пробел
20 0 5 1 b1= 1____
Редактирование - пробел
20 0 5 1 a0= 1____
Редактирование - пробел
20 0 5 1 b0= 1____
Редактирование - пробел
20 0 5 1 ac= 1____
Редактирование - пробел
20 0 5 1 bc= 1____
Редактирование - пробел
20 0 4 1 A= -1___
Редактирование - пробел
20 0 4 1 B= 1____
Редактирование - пробел
1 2
18 1 -1 1 Ввод y"=f(x,y,y')                   @
Ввод правой части уравнения
18 1 -1 1 Краевые усл.,нач. прибл. и точность @
Ввод параметров задачи
1 1
20 1 12 1 f(x,y,y')= -y'-1000*y____________________
Редактирование - пробел
2 6
20 0 5 1 a1= 1____
Редактирование - пробел
20 0 5 1 b1= 1____
Редактирование - пробел
20 0 5 1 a0= 1____
Редактирование - пробел
20 0 5 1 b0= 1____
Редактирование - пробел
20 0 5 1 ac= 1____
Редактирование - пробел
20 0 5 1 bc= 1____
Редактирование - пробел
20 0 4 1 A= -1___
Редактирование - пробел
20 0 4 1 B= 1____
Редактирование - пробел
20 0 4 1 y0= 1____
Редактирование - пробел
20 0 6 1 y'0= 1____
Редактирование - пробел
20 0 6 1 eps= 1e-7_
Редактирование - пробел
20 0 4 1 N= 200_
Редактирование - пробел
1 5
-1 1 -1 1 Стереть графики_
Очистка графиков и памяти
19 1 -1 1( ) Окно с информацией_
Выдача информации
-1 1 -1 1( ) Окно с подсказкой_
Выдача подсказки
-1 1 -1 1( ) Окно с производной_
Выдача графика производной
5 1 -1 1 Восстановить экран_
Перерисовка всего экрана
1 2
13 1 -1 1 Ввод f(x,y,y') и y0(x)  @
Правая часть и нач. прибл.
13 1 -1 1 Краевые усл. и точность @
Ввод параметров
1 2
20 1 12 1 f(x,y,y')= -y'-1000*y____________________
Редактирование - пробел
20 1 8 1 y0(x)= x*x_________________________
Редактирование - пробел
2 5
20 0 5 1 a1= 1____
Редактирование - пробел
20 0 5 1 b1= 1____
Редактирование - пробел
20 0 5 1 a0= 1____
Редактирование - пробел
20 0 5 1 b0= 1____
Редактирование - пробел
20 0 5 1 ac= 1____
Редактирование - пробел
20 0 5 1 bc= 1____
Редактирование - пробел
20 0 4 1 A= -1___
Редактирование - пробел
20 0 4 1 B= 1____
Редактирование - пробел
20 0 6 1 eps= 1.0e-7_
Редактирование - пробел
20 0 4 1 N= 200_
Редактирование - пробел
1 6
4 0 -1 0  Основы вычислительной математики.
Информация о авторах
-1 0 -1 0           Краевые задачи
-1 0 -1 0 141700,г.Долгопрудный Московской обл.,
-1 0 -1 0      Институтский пер., 9 ,МФТИ,
-1 0 -1 0   кафедра вычилительной математики,
-1 0 -1 0      Телефон: (095) 408-72-27.
1 4
21 1 -1 1 Сохранить задачу @
Сохранение всех параметров
8 1 -1 1 Загрузить задачу @
Загрузка всех параметров
22 2 -1 1 Сохранить экран  @
Сохранение изображения
0 1 -1 1 Выход    <Alt-X>
Окончание работы
1 1
9 1 20 1 Введите имя файла: edgedat1.dat
Редактирование - пробел
1 1
9 1 20 1 Введете имя файла: edgeimg1.pcx
Редактирование - пробел
1 2
23 1 -1 1 Масштабировать графики_
Вывод с масштабированием
23 1 -1 1 Не масштабировать графики_
Вывод без масштабирования
1 4
0 1 -1 1 Клавиши_
Назначение клавиш
1 1 -1 1 Задачник_
Выдача задачника
17 1 -1 1 Учебник_
Выдача учебника
0 1 -1 1 Индекс_
Список тем по алфавиту_