7 1
0 0 -1 1_*__
Информация о производителе
1 0 -1 1__Файлы__
Работа с периферийными устройствами
2 0 -1 1__Окна__
Задание конфигурации окон
3 0 -1 1__Запуск___
Запуск метода на счет
4 0 -1 1__Методы__
Выбор метода вычислений
5 0 -1 1__Параметры___
Параметры для вычислений
6 0 -1 1__Помощь___
Помощь по работе с програмой
1 9
-1 0 -1 0   Решение уравнений эллиптического типа
Информация о производителе
-1 0 -1 0_         Уравнение Пуассона
Информация о производителе
-1 0 -1 0                141 700
Информация о производителе
-1 0 -1 0   г. Долгопрудный Московской области
Информация о производителе
-1 0 -1 0         Институтский переулок 9,
Информация о производителе
-1 0 -1 0 Московский физико - технический институт,_
Информация о производителе
-1 0 -1 0    кафедра вычислительной математики.
Информация о производителе
-1 0 -1 0_
Информация о производителе
-1 0 -1 0     Телефон : ( 095 ) 408 - 72 - 27
Информация о производителе
1 3
-1 4 -1  1Сохранить экран @_
Редактор - <SPACE>,сохранение - <ENTER>.
-1 4 -1  0Печать на принтер
Печать на принтер - <ENTER>
-1 4 -1  1Выход (Alt-X)
Выход из программы.
1 7
-1 0 -1 0 Правая часть уравнения Пуассона
-1 0 9 1f(x,y) = 5*sin(x)*cos(y)_________
Редактор функции - <SPACE>.
-1 0 26 1Число разбиений области = 9_
Редактор числа разбиений - <SPACE>.
-1 0 30 0Максимальное число итераций = 100__
Редактор числа итераций - <SPACE>.
-1 0 25 0Допустимая погрешность = 1e-3_____
Редактор погрешности - <SPACE>.
-1 0 -1 0 Коэффициент в нелинейном уравнении
-1 0 9 1L(x,y) = 1.0_____________________
Редактор функции - <SPACE>.
1 5
-1 4 -1 1(*) Решение задачи_
Окно с решением (вкл/выкл).
-1 4 -1 1(*) Правая часть
Окно с функцией в правой части (вкл/выкл).
-1 4 -1 1(_) Погрешность вычислений_
Окно с полем погрешностей (вкл/выкл).
-1 4 -1 1(_) Окно с информацией_
Окно с информацией о методах (вкл/выкл).
-1 4 -1 1(_) Строка подсказки
Окно со строкой подсказки (вкл/выкл).
1 6
-1 4 -1 1(*) Дискретного преобразования Фурье_
Выбор данного метода - <ENTER>
-1 4 -1 1(_) Простых итерации
Выбор данного метода - <ENTER>
-1 4 -1 1(_) Переменных направлений
Выбор данного метода - <ENTER>
-1 4 -1 1(_) Сопряженных градиентов
Выбор данного метода - <ENTER>
-1 4 -1 1(_) Трехслойный итерационный метод Чебышева_
Выбор данного метода - <ENTER>
-1 4 -1 1(_) Метод спектрально эквивалентных операторов_
Выбор данного метода - <ENTER>
1 1
-1 0 7 1Файл:  puasson.pcx_
Редактор файла <SPACE>. 
1 4
-1 0 -1 1 Клавиатура_
Основные клавиши для начала работы
-1 0 -1 1 Учебник
Теоретическая информация по методам
-1 0 -1 1 Задачник
Предлагаемый учебный маршрут
-1 0 -1 1 Индекс
Список тем по алфавиту

